apiVersion: apps/v1
kind: Deployment
metadata:
  name: ken-cache
  namespace: ken-system
  labels:
    app: ken-cache
    component: cache
    version: 2.0.0-quintillion
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ken-cache
  template:
    metadata:
      labels:
        app: ken-cache
        component: cache
    spec:
      containers:
      - name: redis
        image: redis:7-alpine
        ports:
        - containerPort: 6379
        command:
        - redis-server
        - --maxmemory
        - 1gb
        - --maxmemory-policy
        - allkeys-lru
        - --save
        - "900 1"
        - --save
        - "300 10"
        - --save
        - "60 10000"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        volumeMounts:
        - name: redis-data
          mountPath: /data
        livenessProbe:
          exec:
            command:
            - redis-cli
            - ping
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          exec:
            command:
            - redis-cli
            - ping
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: redis-data
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: ken-cache
  namespace: ken-system
spec:
  selector:
    app: ken-cache
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379
  type: ClusterIP

